- name: "SHOW CREDS"
  hosts: localhost
  connection: local
  gather_facts: no


  vars_files:
    - "{{ playbook_dir }}/vars/secrets.yml"

  tasks:
    - name: "SHOW THE S3CR3t$"
      debug:
        msg: "SUPERSECRETUSERNAME: {{ ansible_user }} @^@ HAXXORPASSWD: {{ ansible_ssh_pass }}"
